import os
import webbrowser
from datetime import datetime
from markdown import markdown

HTML_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Future Trends Report</title>
<style>
  :root {{ --bg: #0f172a; --card: #1e293b; --accent: #38bdf8; --text: #e2e8f0; --muted: #94a3b8; }}
  * {{ margin: 0; padding: 0; box-sizing: border-box; }}
  body {{ background: var(--bg); color: var(--text); font-family: 'Segoe UI', system-ui, sans-serif; line-height: 1.7; padding: 40px 20px; }}
  .container {{ max-width: 900px; margin: 0 auto; }}
  header {{ text-align: center; margin-bottom: 40px; }}
  header h1 {{ font-size: 2.2rem; background: linear-gradient(90deg, #38bdf8, #a78bfa); -webkit-background-clip: text; background-clip: text; color: transparent; }}
  header p {{ color: var(--muted); margin-top: 8px; }}
  .report-body {{ background: var(--card); border: 1px solid #334155; border-radius: 16px; padding: 32px; }}
  .report-body h3 {{ color: var(--accent); margin: 28px 0 12px; font-size: 1.3rem; }}
  .report-body h3:first-child {{ margin-top: 0; }}
  .report-body ul {{ margin: 8px 0 8px 24px; }}
  .report-body li {{ margin-bottom: 6px; }}
  .report-body strong {{ color: #fbbf24; }}
  footer {{ text-align: center; color: var(--muted); margin-top: 32px; font-size: 0.85rem; }}
</style>
</head>
<body>
<div class="container">
  <header>
    <h1>🔮 Future Trends Report</h1>
    <p>Generated by the Multi-Agent Marketing Research Team on {date}</p>
  </header>
  <div class="report-body">
{content}
  </div>
  <footer>Built with LangGraph + LangChain • Powered by Qwen2.5-3B (local)</footer>
</div>
</body>
</html>
"""

def render_report(markdown_text: str, open_in_browser: bool = True) -> str:
    os.makedirs("reports", exist_ok=True)
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    filename = f"reports/trend_report_{timestamp}.html"

    html_content = markdown(markdown_text, extensions=["extra"])
    full_html = HTML_TEMPLATE.format(
        date=datetime.now().strftime("%B %d, %Y at %H:%M"),
        content=html_content
    )

    with open(filename, "w", encoding="utf-8") as f:
        f.write(full_html)

    print(f"📄 HTML report saved to {filename}")

    if open_in_browser:
        webbrowser.open("file:///" + os.path.abspath(filename))

    return filename
